packages:
  - 'apps/*'

overrides:
  ajv>fast-uri: 3.1.2
  next>postcss: 8.5.10
  minimatch>brace-expansion: 5.0.6
  puppeteer-core>ws: 8.20.1
  superagent>qs: 6.15.2
  express>qs: 6.15.2
  body-parser>qs: 6.15.2
